FROM golang:1.16.5

USER root

ENV K6_HOME /home/k6
ENV K6_TESTS /opt/

RUN mkdir $K6_HOME && \
    chmod -R a+rwX $K6_HOME && \
    cd $K6_HOME && \

    # install xk6
    wget https://github.com/k6io/xk6/releases/download/v0.4.1/xk6_0.4.1_linux_amd64.tar.gz && \
    tar -xvzf xk6_0.4.1_linux_amd64.tar.gz && \

    # build prometheus module
    ./xk6 build --with github.com/szkiba/xk6-prometheus@latest && \
    rm -rf xk6_0.4.1_linux_amd64.tar.gz xk6 LICENSE README.md && \
    ln -s /home/k6/k6 /usr/bin/k6 && \

    # install dependencies
    apt-get install git

COPY entrypoint.sh /

WORKDIR $K6_HOME
ENTRYPOINT ["/entrypoint.sh"]