FROM golang:1.21.4-alpine3.18

USER root
ENV K6_HOME /home/k6

COPY entrypoint.sh /
RUN mkdir $K6_HOME && \
    chmod -R a+rwX $K6_HOME && \
    apk update && \
    apk add --no-cache \
    git && \
    go install go.k6.io/xk6/cmd/xk6@latest
RUN cd $K6_HOME && \
    xk6 build --with github.com/szkiba/xk6-prometheus@latest && \
    chmod +x ./k6


WORKDIR $K6_HOME
ENTRYPOINT ["/entrypoint.sh"]