{
 "title": "K6 performance observability",
 "tags": [
  "k6",
  "PerformanceTesting"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "tc",
    "label": "tc",
    "query": {
     "query": "label_values(k6_http_req_duration_seconds,tc)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Duration (k6)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, tc, group, type, method) (\n    rate(k6_http_req_duration_seconds{tc=~\"$tc\"}[1m])\n  )\n) * 1000\n",
     "legendFormat": "Duration {{group}}"
    }
   ]
  },
  {
   "title": "Total VU Current (k6)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "k6_vus", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests (k6)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "k6_http_reqs_total", "legendFormat": "Requests {{group}} {{type}}" }
   ]
  },
  {
   "title": "VU (k6)",
   "type": "timeseries",
   "description": "Current number of active virtual users",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 15 },
   "targets": [
    { "expr": "k6_vus", "legendFormat": "VU total" },
    { "expr": "k6_vus_max", "legendFormat": "VU max" }
   ]
  }
 ]
}