apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: k6-baseline
  namespace: k6
spec:
  selector:
    matchLabels:
      app: k6
  serviceName: "k6-load-generator"
  replicas: 2
  template:
    metadata:
      labels:
        app: k6
        test: load
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: "In"
                  values: [ "k6" ]
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: k6
        image: quay.io/rdpanek/k6:0.47.0
        args: ["-o", "experimental-prometheus-rw", "--insecure-skip-tls-verify", "--no-usage-report"]
        env:
        - name: GIT_REVISION
          value: "a5329f2"
        - name: TEST_PLAN_NAME
          value: "./demos/01-sandbox/04-prometheus.js"
        - name: GIT_TEST_REPOSITORY
          value: "https://github.com/rdpanek/k6.git"
        - name: ENV_PRINT
          value: "allow"
        - name: K6_PROMETHEUS_RW_SERVER_URL
          value: "http://prometheus.k6.svc.cluster.local/api/v1/write"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "6Gi"
            cpu: "2"
        imagePullPolicy: "Always"