apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: k6-baseline
  namespace: k6
spec:
  selector:
    matchLabels:
      app: k6
  serviceName: "k6-load-generator"
  replicas: 2
  template:
    metadata:
      labels:
        app: k6
        test: load
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: "In"
                  values: [ "k6" ]
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: k6
        image: ghcr.io/rdpanek/k6:prom.latest
        args:
          - "-o"
          - "experimental-prometheus-rw"
          - "--summary-mode=disabled"
          - "--no-thresholds"
          - "--verbose"
        env:
        - name: GIT_REVISION
          value: "0a36a87"
        - name: TEST_PLAN_NAME
          value: "demos/01-sandbox/04-prometheus.js"
        - name: GIT_TEST_REPOSITORY
          value: "https://github.com/rdpanek/k6.git"
        - name: K6_PROMETHEUS_RW_SERVER_URL
          value: "http://prometheus.k6.svc.cluster.local/api/v1/write"
        - name: K6_PROMETHEUS_RW_PUSH_INTERVAL
          value: "5s"
        - name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
          value: "true"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "6Gi"
            cpu: "2"
        imagePullPolicy: "Always"
