apiVersion: batch/v1
kind: CronJob
metadata:
  name: k6-smoke
  namespace: k6
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 2
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k6
            image: ghcr.io/rdpanek/k6:prom.latest
            args:
              - "-o"
              - "experimental-prometheus-rw"
              - "--summary-mode=disabled"
              - "--no-thresholds"
            env:
            - name: GIT_REVISION
              value: "0a36a87"
            - name: TEST_PLAN_NAME
              value: "demos/01-sandbox/04-prometheus.js"
            - name: GIT_TEST_REPOSITORY
              value: "https://github.com/rdpanek/k6.git"
            - name: K6_PROMETHEUS_RW_SERVER_URL
              value: "http://prometheus.k6.svc.cluster.local/api/v1/write"
            - name: K6_PROMETHEUS_RW_PUSH_INTERVAL
              value: "5s"
            - name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
              value: "true"
            resources:
              requests:
                memory: "1Gi"
                cpu: "0.5"
              limits:
                memory: "2Gi"
                cpu: "2"
            imagePullPolicy: "Always"
          restartPolicy: "Never"
