{
 "title": "K6 performance observability Copy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "VU (k6)",
   "type": "timeseries",
   "description": "Current number of active virtual users",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 0 },
   "targets": [
    { "expr": "k6_vus", "legendFormat": "{{vu}}" }
   ]
  },
  {
   "title": "Total VU Current (k6)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "k6_vus" }
   ]
  },
  {
   "title": "HTTP transactions (k6)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "k6_http_req_duration_p95{expected_response=\"true\"}",
     "legendFormat": "Duration {{group}}"
    },
    {
     "expr": "k6_http_req_waiting_p95{expected_response=\"true\"}",
     "legendFormat": "TTFB {{group}}"
    }
   ]
  },
  {
   "title": "HTTP TTFB Current (k6)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k6_http_req_waiting_p95{expected_response=\"true\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "HTTP Duration Current (k6)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k6_http_req_duration_p95{expected_response=\"true\"}"
    }
   ]
  },
  {
   "title": "Request failed  (k6)",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "count by(status) (k6_http_req_failed)",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}